FROM node:lts-alpine as builder

WORKDIR /usr/src/app

RUN apk update && apk add bash

COPY . .

RUN npm install

RUN npm run build


FROM jboss/keycloak:latest

WORKDIR /opt/jboss/keycloak

COPY keycloak/disable-theme-cache.cli ../startup-scripts/disable-theme-cache.cli

COPY --from=builder /usr/src/app/theme ./themes/fgpe

EXPOSE 8080

